
[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501
showWarningOnDirectExecution = true

[global]
developmentMode = false
showWarningOnDirectExecution = true

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
liveSave = false

[theme]
base = "light"

[s3]
bucket = ""

[viewer]
maxRetries = 5
useLatencyBuffer = true

[mapbox]
token = ""
style = "mapbox://styles/mapbox/streets-v11"

[deprecation]
showfileUploaderEncoding = false
showPyplotGlobalUse = false

[logger]
level = "info"

[client]
displayEnabled = true


[browser]
hideFooter = true

